project13/urls.py
from django.contrib import admin
from django.urls import path,include
from genericapp.views import *

import specificapp


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Ram/',Ram,name='Ram'),
    path('chotu/',chotu,name='chotu'),

    path('specificapp/',include('specificapp.urls')),
]

specificapp/urls.py
from specificapp.views import *

from django.urls import path

app_name='something'

urlpatterns=[

    path('bittu/',bittu,name='bittu'),
    path('Ramesh/',Ramesh,name='Ramesh'),
]

genericapp/models.py
from django.db import models

# Create your models here.

runserver/models.py
from django.db import models

# Create your models here.

specificapp/models.py
from django.db import models

# Create your models here.

genericapp/views.py
from django.shortcuts import render

# Create your views here.

def Ram(request):
    return render(request,'Ram.html')


def chotu(request):
    return render(request,'chotu.html')

runserver/views.py
from django.shortcuts import render

# Create your views here.

specificapp/views.py
from django.shortcuts import render

# Create your views here.


def bittu(request):
    return render(request,'bittu.html')

def Ramesh(request):
    return render(request,'Ramesh.html')

templates/Ram.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color: blue;">HII HELLO CHOTU</h1>
        <h1 style="color: red;">WHERE ARE YOU</h1>
        <h1 style="color: green;">DID YOU GO TO SCHOOL OR NOT</h1>

        <a href="{% url 'chotu' %}"><h2>chotu response</h2></a>

        <a href="{% url 'something:bittu' %}"><h2>bittu response</h2></a>

        <a href="{% url 'something:Ramesh' %}"><h2>Ramesh response</h2></a>

    </center>
</body>
</html>

templates/Ramesh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color: aqua;">HAA BITTU,CHOTU</h1>
        <h1 style="color: blue;">TINNA MERU TINNARA</h1>
        <h1 style="color: red;">CHADUVUKUNNARA</h1>
        <h1 style="color: crimson;">HOMEWORK CHESARA</h1>

        <a href="{% url 'chotu' %}"><h2>chotu response</h2></a>

        <a href="{% url 'something:bittu' %}"><h2>bittu response</h2></a>

        <a href="{% url 'Ram' %}"><h2>Ram response</h2></a>
    </center>
</body>
</html>

templates/bittu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color: blueviolet;">HI HELLO MAMA</h1>
        <h1 style="color: red;">BAGUNNAVA MAMA</h1>
        <h1 style="color: yellowgreen;">EM CHESTUNNAV MAMA</h1>

        <a href="{% url 'chotu' %}"><h2>chotu response</h2></a>

        <a href="{% url 'Ram' %}"><h2>Ram response</h2></a>

        <a href="{% url 'something:Ramesh' %}"><h2>Ramesh response</h2></a>
    </center>
</body>
</html>

templates/chotu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color: green;">HELLO MAMA</h1>
        <h1 style="color: blue;">SCHOOL KI VELLI VACHINA MAMA</h1>
        <h1 style="color: red;">TINTUNNA MAMA</h1>

        <a href="{% url 'Ram' %}"><h2>Ram response</h2></a>

        <a href="{% url 'something:bittu' %}"><h2>bittu response</h2></a>

        <a href="{% url 'something:Ramesh' %}"><h2>Ramesh response</h2></a>
    </center>
</body>
</html>